name: "build"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  build-win:
    name: "Build windows"
    runs-on: "windows-2016"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        repository:  openjdk/jdk8u-dev
        path: jdk8u-dev
      - uses: actions/setup-java@v1
        with:
          java-version: '7'
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          install: base-devel curl tar zip unzip
      - name: Instal vc2010
        run: choco install vcexpress2010
      - name: Run build
        shell: msys2 {0}
        run: |
          set -eux
          # https://github.community/t/how-to-use-vc100-for-msbuild/16623/2
          curl -f -L -o "freetype-windows-binaries-2.10.2.tar.gz" "https://github.com/ubawurinna/freetype-windows-binaries/archive/v2.10.2.tar.gz"
          tar -xf "freetype-windows-binaries-2.10.2.tar.gz"
          cp -a "freetype-windows-binaries-2.10.2/win32" "freetype-windows-binaries-2.10.2/lib"
          freetypeDir="$( readlink -f freetype-windows-binaries-2.10.2 )"

          cd jdk8u-dev
          sed -i 's@\$CC \$FIXPATH_SRC@FIXPATH_SRC=$( echo $FIXPATH_SRC | tr "/" "\\\\" ) ; FIXPATH_BIN=$( echo $FIXPATH_BIN | tr "/" "\\\\" ) ; echo FIXPATH_SRC: $FIXPATH_SRC ; echo FIXPATH_BIN: $FIXPATH_BIN ; $CC $FIXPATH_SRC@g' common/autoconf/generated-configure.sh

          bash ./configure --with-boot-jdk="${JAVA_HOME}" --with-toolchain-version=2010 --with-msvcr-dll='C:\Windows\SysWOW64\msvcr100.dll' --with-target-bits=32 --enable-debug --enable-unlimited-crypto --enable-jfr --with-freetype="${freetypeDir}"
          make images
          ls build
          ls build/*/images
