name: "build"

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:
  test-auto:
    name: "Build"
    runs-on: "ubuntu-16.04"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-top
          path: jdkforest
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-corba
          path: jdkforest/corba
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-hotspot
          path: jdkforest/hotspot
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jaxp
          path: jdkforest/jaxp
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jaxws
          path: jdkforest/jaxws
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jdk
          path: jdkforest/jdk
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-langtools
          path: jdkforest/langtools
          ref: 'jdk8u272-b08'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-nashorn
          path: jdkforest/nashorn
          ref: 'jdk8u272-b08'
      - uses: actions/setup-java@v1
        with:
          java-version: '7'
      - name: Run
        run: |
          bash ./configure --with-boot-jdk="${JAVA_HOME}" --enable-debug --enable-unlimited-crypto --enable-jfr
          make images

