name: "build"

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:
  gen-src-archive:
    name: "Generate source archive"
    runs-on: "ubuntu-latest"
    if: false
    steps:
      - uses: actions/checkout@v2
      - name: checkout jdkforest-top
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-top
          path: jdkforest
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-corba
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-corba
          path: jdkforest/corba
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-hotspot
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-hotspot
          path: jdkforest/hotspot
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-jaxp
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jaxp
          path: jdkforest/jaxp
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-jaxws
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jaxws
          path: jdkforest/jaxws
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-jdk
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jdk
          path: jdkforest/jdk
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-langtools
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-langtools
          path: jdkforest/langtools
          ref: 'jdk8u272-b08'
      - name: checkout jdkforest-nashorn
        uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-nashorn
          path: jdkforest/nashorn
          ref: 'jdk8u272-b08'
      - name: Run
        run: |
          tar -cJf jdkforest.tar.xz --exclude-vcs jdkforest
      - uses: eine/tip@master
        with:
          tag: build-latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            jdkforest.tar.xz

  build-win:
    name: "Build windows"
    runs-on: "windows-2016"
    #needs: gen-src-archive
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '7'
      - uses: msys2/setup-msys2@v2
        with:
          update: false
          install: base-devel curl tar unzip
      - name: Run
        run: |
          curl -f -L -o "jdkforest.tar.xz" "https://github.com/zzambers/test-jdk-builder/releases/download/build-latest/jdkforest.tar.xz"
          tar -xJf "jdkforest.tar.xz"
          cd jdkforest
          bash ./configure --with-boot-jdk="${JAVA_HOME}" --enable-debug --enable-unlimited-crypto --enable-jfr
          make images
          ls build
          ls build/*/images


  build-native:
    name: "Build native"
    runs-on: "ubuntu-16.04"
    #needs: gen-src-archive
    if: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '7'
      - name: Run
        run: |
          #curl -f -L -o "jdkforest.tar.xz" "https://github.com/zzambers/test-jdk-builder/releases/download/build-latest/jdkforest.tar.xz"
          #tar -xJf "jdkforest.tar.xz"
          #sudo apt-get install libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
          #sudo apt-get install libcups2-dev
          #sudo apt-get install libasound2-dev
          #cd jdkforest
          #bash ./configure --with-boot-jdk="${JAVA_HOME}" --enable-debug --enable-unlimited-crypto --enable-jfr
          #make images
          #ls build
          #ls build/*/images
