name: "build"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build-win:
    name: "Build windows"
    runs-on: "windows-2016"
    steps:
      - uses: actions/checkout@v2
        with:
          repository:  openjdk/jdk8u-dev
          path: jdk8u-dev
      - uses: actions/setup-java@v1
        with:
          java-version: '7'
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          install: base-devel curl tar zip unzip p7zip
      - name: Cache VS2010Express1.iso
        uses: actions/cache@v2
        with:
          path: |
            VS2010Express1.iso
          key: VS2010Express1.iso
      - name: Download and unpack VS2010Express1.iso
        shell: msys2 {0}
        run: |
          set -eux
          # https://github.community/t/how-to-use-vc100-for-msbuild/16623/2
          if ! [ -f "VS2010Express1.iso" ] ; then
              curl -f -L -o "VS2010Express1.iso" "https://web.archive.org/web/20140227220734if_/http://download.microsoft.com/download/1/E/5/1E5F1C0A-0D5B-426A-A603-1798B951DDAE/VS2010Express1.iso"
          fi
          mkdir VS2010Express1
          7z x -oVS2010Express1 "VS2010Express1.iso"
      - name: Install VS2010Express
        shell: cmd
        run: |
          ${{ github.workspace }}\VS2010Express1\VCExpress\setup.exe /q /norestart
      - name: Run build
        shell: msys2 {0}
        run: |
          set -eux

          curl -f -L -o "freetype-windows-binaries-2.10.2.tar.gz" "https://github.com/ubawurinna/freetype-windows-binaries/archive/v2.10.2.tar.gz"
          tar -xf "freetype-windows-binaries-2.10.2.tar.gz"
          cp -a "freetype-windows-binaries-2.10.2/win32" "freetype-windows-binaries-2.10.2/lib"
          freetypeDir="$( readlink -f freetype-windows-binaries-2.10.2 )"

          cd jdk8u-dev
          # MSYS2_ARG_CONV_EXCL is workaround to prevent unwanted/wrong path
          # conversion in CC arg by msys2 ( -FeD:/a/... -> -FeD:A:/... )
          # in common/autoconf/generated-configure.sh
          #    $CC $FIXPATH_SRC -Fe$FIXPATH_BIN > $OUTPUT_ROOT/fixpath1.log 2>&1
          workspaceDir='${{ github.workspace }}'
          MSYS2_ARG_CONV_EXCL="-Fe${workspaceDir%%:*}:/" bash ./configure --with-boot-jdk="${JAVA_HOME}" --with-toolchain-version=2010 --with-msvcr-dll='C:\Windows\SysWOW64\msvcr100.dll' --with-target-bits=32 --enable-debug --enable-unlimited-crypto --enable-jfr --with-freetype="${freetypeDir}"
          make images
          ls build
          ls build/*/images
          build/*/images/j2sdk-image/bin/java -version
